export enum ProductCategory {
  ELECTRONICS = "Electronics",
  FASHION = "Fashion",
  HOME = "Home",
  SPORTS = "Sports",
  BEAUTY = "Beauty",
  GROCERY = "Grocery",
  APPLIANCES = "Appliances",
  FURNITURE = "Furniture",
  CLOTHING = "Clothing",
  FITNESS = "Fitness",
  MUSIC = "Music",
  GARDEN = "Garden",
  PETS = "Pets",
  BOOKS = "Books",
  TOYS = "Toys",
}
